### ISSUE TITLE
MVP: Manual Sleep Tracking App

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sleep#53]
There are _many_ apps https://github.com/dwyl/sleep/issues/8 and wearable devices https://github.com/dwyl/sleep/issues/7 that people can use for sleep-tracking. 
The issue is that these have a _cost_ and the people using them have **no control of their data**.

I want to build the _bare minimum_ interface for capturing/tracking sleep.
At it's most basic, a sleep tracker is just a stop-watch https://github.com/nelsonic/stopwatch
But rather than simply _discarding_ the **`start`** and **`stop`** times, we record them.

# Todo

+ [ ] Sketch the most basic interface for capturing data
  + [ ] Should be "Dark Mode" by `default` to minimise LED light from device. i.e. light text on a dark background 
  + [ ] Should be Mobile First as this is the device _most_ people look at _last/first_ thing.
+ [ ] Describe the schema for storing the data including person_id using `auth_plug` for authentication!
+ [ ] Build a Basic Phoenix App to capture **`start`** and **`stop`** times for sleep
+ [ ] Integrate Authentication via `auth_plug`
+ [ ] Add ability to add Comments [Later!]
+ [x] Deploy to Heroku? https://dashboard.heroku.com/apps/sleepdev
+ [ ] Start _using_ it to capture my own data!

# Dependent on:

+ [x] `auth` deployment: https://github.com/dwyl/auth/pull/173

My plan is to write this out as a _tutorial_ that a _complete_ beginner can follow similar to all of our [others](https://github.com/search?o=desc&q=topic%3Atutorial+org%3Adwyl+fork%3Atrue&s=updated&type=Repositories).

**Comment by nelsonic** [comment]
Thinking of just using Google Docs / Draw.io to wireframe this ... see: https://github.com/dwyl/learn-wireframing

**Comment by nelsonic** [comment]
Simon has been implementing `auth` in the LiveView Chat app:
https://github.com/dwyl/phoenix-liveview-chat-example/pull/16/files

I think we will do it slightly differently in this **`Sleep`** App because I don't really _want_ to allow "anonymous" use.
API Key: https://authdev.herokuapp.com/apps/3 🔑

**Comment by nelsonic** [comment]
I feel like my lack of sleep - and crucially my poor sleep _communication_ - is holding me back in life. See: https://github.com/dwyl/sleep/issues/46
So I'm bumping up the priority on this and moving it to "In progress" so I will chip away at it over the coming weeks.

**Comment by nelsonic** [comment]
Can you tell what it is yet? 😜 
![phoenix-framerwork-welcome-page](https://user-images.githubusercontent.com/194400/145309471-306fdd5e-324f-4c4a-bd9f-6fddbec7f512.png)

**Comment by nelsonic** [comment]
Continue: 
`~/code/phoenix-liveview-chat-example` 
`~/code/sleep`

(_have to restart my Mac to install updates ..._)

**Comment by nelsonic** [comment]
I'm keen to use our "Prod" Auth instance for this so that there is zero start-up/wait time for using this twice-a-day app.

**Comment by nelsonic** [comment]
Deployed the "Prod" version to Fly.io https://auth.dwyl.com which means that Auth has _zero_ startup time. 
So going to use that to make this mini app.

**Comment by nelsonic** [comment]
https://github.com/dwyl/sleep/tree/basic-sleep-app-issue-%2353

**Comment by nelsonic** [comment]
Tried to `git push` the code I wrote over the weekend as need to close all my non-work tabs to focus on work-work ...
Get the following error:

```sh
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 8 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 2.44 KiB | 1.22 MiB/s, done.
Total 11 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 2 local objects.
remote: Internal Server Error
To github.com:dwyl/sleep.git
 ! [remote rejected] basic-sleep-app-issue-#53 -> basic-sleep-app-issue-#53 (Internal Server Error)
error: failed to push some refs to 'github.com:dwyl/sleep.git'
```

From googling, it looks like GitHub is having a hickup:
https://stackoverflow.com/questions/71514374/im-trying-to-git-push-some-changes-and-i-get-this-internal-server-error
https://github.com/isaacs/github/issues/1253
https://www.githubstatus.com/
<img width="1125" alt="github-status-1" src="https://user-images.githubusercontent.com/194400/159730911-8eb36428-0d92-4ad6-b66c-dda839391640.png">

<img width="1125" alt="github-status-2" src="https://user-images.githubusercontent.com/194400/159730938-5db7dea4-8ec2-4e52-a844-c5e3922e552c.png">

<img width="1125" alt="github-status-3" src="https://user-images.githubusercontent.com/194400/159730984-69266f02-3f97-47c2-9c42-096fa96b6917.png">

Just going to close all the windows and _hope_ that my Laptop doesn't die while GitHub is not working ... ⏳ 

Will continue with this mini side-project on the weekend. 🤞

**Comment by nelsonic** [comment]
Continue: https://github.com/dwyl/sleep/blob/basic-sleep-app-issue-%2353/tutorial.md
