### ISSUE TITLE
Investigate how Sleep Trackers Work

### ISSUE THREAD

**Issue by nelsonic** [dwyl/sleep#8]
This appears to be a good starting point: 
http://www.nosleeplessnights.com/how-do-sleep-trackers-work
[How Do Sleep Trackers Work And Are They Reliable_.pdf](https://github.com/dwyl/sleep/files/995741/How.Do.Sleep.Trackers.Work.And.Are.They.Reliable_.pdf) (_PDF in case the article disappears_) 

## Tasks / Todo
+ [ ] Do research into sleep tracking wearables, apps and devices
+ [ ] Write a summary of the existing research.

Please summarise your findings in the README of this repo. thanks! 🎉 
(_if the research get's "too big" we can always split it out into a separate file e.g: `sleep-tracker-research.md` and link to it from the main README..._)

**Comment by sohilpandya** [comment]
I've looked at a list of apps for the apple watch.
- [ ] [Sleep++](https://itunes.apple.com/gb/app/sleep/id1038440371?mt=8&ign-mpt=uo%3D4)
- [ ] [Sleep Diary](https://itunes.apple.com/gb/app/sleep/id1038440371?mt=8&ign-mpt=uo%3D4)
- [ ] [Sleep Tracker](https://itunes.apple.com/gb/app/sleep-tracker-auto-sleep-tracking-watch-monitor/id1179236591?mt=8&ign-mpt=uo%3D4)
- [x] [AutoSleep](https://itunes.apple.com/gb/app/autosleep-auto-sleep-tracker-for-watch/id1164801111?mt=8&ign-mpt=uo%3D4)

I've selected [AutoSleep](https://itunes.apple.com/gb/app/autosleep-auto-sleep-tracker-for-watch/id1164801111?mt=8&ign-mpt=uo%3D4) as the one to test out, I'll post my result of how accurately it seems to measure my sleep, but from doing some reading it looks like most of these apps use a combination of movement and heart rate to calculate how well you slept. 

## Research for Readme

Sleep can be tracked using a couple of main methods. 
- **Polysomnography** 
  Usually referred to as the **gold standard** in sleep measurement. It involved the patient having to stay at a sleep centre where the doctors would measure information using various pieces of equipment and provide a very accurate review. 

| pros | cons |
| ---- | ---- |
| accurate | requires patient to be in a center |
| Lots of data can be collected. (flow of air, muscle activity, oxygen levels) | requires patient to be in a controlled environment, they may not be able to sleep naturally | 

- **Actigraphy**
  A non-invasive method for monitoring sleep cycles. Usually, comes in a form of a wristband which contains accelerometer. The movement along with some algorithms are used to determine the sleep of a patient. There are lots of wearable devices that can use this.

| pros | cons |
| ---- | ---- |
| non-invasive | doesn't provide accurate and detailed data in comparison to Polysomnography |
| cheaper than Polysomnography |  |
| patients can wear this on a daily basis and be able to sleep naturally | |

- **Actigraphy ++** 
  There are a lot of wearable devices that now come with a built-in heart-rate monitor, this provides another piece of vital information which can be used to determine how well the patient is sleeping. Some of the apps above use the combination of movement and heart rate to determine a patient's sleep and that is what we'll be researching. How well do some of these apps work in terms of accuracy
